server:
  port: 40000


spring:
  profiles:
    active: dev

  application:
    name: cart

  redis:
    port: 6379
    host: 81.70.10.9
    password: Diao0707

thread-pool:
  core-size: 20
  max-size: 200
  keep-alive-time: 10


ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000


