spring:
  profiles:
    active: dev
  cloud:
    gateway:
        routes:
          - id: product_route
            uri: lb://product
            predicates:
              - Path=/api/product/**
            filters:
              - RewritePath=/api/(?<segment>.*),/$\{segment}

          - id: auth_route
            uri: lb://auth-server
            predicates:
              - Path=/api/auth/**
            filters:
              - RewritePath=/api/(?<segment>.*),/$\{segment}

          - id: member_route
            uri: lb://member
            predicates:
              - Path=/api/member/**
            filters:
              - RewritePath=/api/(?<segment>.*),/$\{segment}

          - id: third_party_route
            uri: lb://third-party
            predicates:
              - Path=/api/thirdparty/**
            filters:
              - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

          - id: ware_route
            uri: lb://ware
            predicates:
              - Path=/api/ware/**
            filters:
              - RewritePath=/api/(?<segment>.*),/$\{segment}

          - id: search_route
            uri: lb://search
            predicates:
              - Path=/api/search/**
            filters:
              - RewritePath=/api/(?<segment>.*),/$\{segment}

          - id: cart
            uri: lb://cart
            predicates:
              - Path=/api/cart/**
            filters:
              - RewritePath=/api/(?<segment>.*),/$\{segment}

          - id: order
            uri: lb://order
            predicates:
              - Path=/api/order/**
            filters:
              - RewritePath=/api/(?<segment>.*),/$\{segment}

          - id: admin_route
            uri: lb://admin
            predicates:
              - Path=/api/**
            filters: # 这段过滤器和验证码有关，api内容缓存了/renren-fast，还得注意/renren-fast也注册到nacos中
              - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}


  application:
    name: gateway

server:
  port: 88
