spring:
  profiles:
    active: dev
  application:
    name: search
  redis:
    port: 6379
    host: 81.70.10.9
    password: Diao0707


  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/

server:
  port: 7070

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
